@extends('layouts.app')

@section('title', 'Service Recommendations')

@section('content')
<div class="container mx-auto p-4 md:p-12">
    <div class="max-w-7xl mx-auto">
        
        <!-- Header Section -->
        <header class="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-6">
            <div>
                <div class="inline-flex items-center space-x-2 px-3 py-1 bg-indigo-50 text-indigo-700 rounded-full text-[10px] font-black uppercase tracking-widest mb-4">
                    <span class="flex h-2 w-2 rounded-full bg-indigo-600"></span>
                    <span>System Diagnostic Report</span>
                </div>
                <h1 class="text-5xl font-black text-gray-900 leading-tight tracking-tighter uppercase italic">
                    Analysis <span class="text-indigo-600">Results</span>
                </h1>
                <p class="text-xl text-gray-500 mt-2 font-medium italic">Comprehensive maintenance roadmap generated by the AI Engine.</p>
            </div>
            
            <a href="{{ route('ai.index') }}" class="group inline-flex items-center px-6 py-3 bg-gray-100 text-gray-800 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-gray-200 transition-all">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 transform group-hover:-translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                Back to Recommender
            </a>
        </header>

        <div class="flex flex-col lg:flex-row gap-12 items-stretch min-h-[70vh]">
            
            <!-- Left Side: Vehicle Context Card -->
            <div class="w-full lg:w-1/3 flex sticky top-24">
                <div class="bg-slate-900 p-12 rounded-[3rem] shadow-2xl flex flex-col items-center justify-between w-full border-4 border-indigo-500/30 group">
                    
                    <div class="w-full flex flex-col items-center">
                        <div class="h-48 w-full rounded-3xl bg-indigo-600 flex items-center justify-center border-4 border-white shadow-2xl rotate-3 mb-8 group-hover:rotate-0 transition-transform duration-500 overflow-hidden">
                            {{-- Car Image Placeholder / or real image if added in future --}}
                            <img src="{{ asset('images/car1.jpg') }}"  class="w-full h-full object-cover group-hover/img:scale-110 transition-transform duration-500">
                            {{-- <svg xmlns="http://www.w3.org/2000/svg" class="h-20 w-20 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                            </svg> --}}
                        </div>
                        <h2 class="text-3xl font-black text-white tracking-tighter uppercase italic text-center leading-none">2020 Honda Civic</h2>
                        <div class="mt-4 px-4 py-1 bg-white/10 rounded-full">
                            <span class="text-[9px] font-black text-indigo-300 uppercase tracking-widest">Active Fleet Asset</span>
                        </div>
                    </div>

                    <!-- Report Metadata -->
                    <div class="mt-12 w-full space-y-4">
                        <div class="bg-white/5 p-5 rounded-2xl border border-white/10">
                            <p class="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-1">Analysis Date</p>
                            <p class="text-white font-black italic">{{ now()->format('d M Y') }}</p>
                        </div>
                        <div class="bg-white/5 p-5 rounded-2xl border border-white/10">
                            <p class="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-1">Model Accuracy</p>
                            <p class="text-emerald-400 font-black italic">98.2% Confidence</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Right Side: Recommendations List -->
            <div class="w-full lg:w-2/3 flex flex-col space-y-8">
                
                <h3 class="text-xs font-black text-gray-900 uppercase tracking-[0.2em] mb-2 italic">Priority Service Roadmap</h3>

                {{-- Recommendation Card 1 --}}
                <div class="group relative bg-white p-8 rounded-[2.5rem] border border-gray-100 shadow-xl shadow-gray-200/50 transition-all duration-500 hover:shadow-indigo-500/10 hover:-translate-y-1 border-l-8 border-l-red-500">
                    <div class="flex flex-col md:flex-row items-center gap-8">
                        <div class="shrink-0 h-16 w-16 bg-red-50 text-red-500 rounded-2xl flex items-center justify-center font-black italic text-2xl">01</div>
                        
                        <div class="flex-1 text-center md:text-left">
                            <h4 class="text-2xl font-black text-gray-900 tracking-tight uppercase italic leading-none">Engine Diagnostic</h4>
                            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-2">Critical System Analysis</p>
                        </div>

                        <div class="text-center md:text-right">
                            <p class="text-2xl font-black text-gray-900 tracking-tighter italic">RM 250.00</p>
                            <div class="mt-2 inline-flex items-center px-3 py-1 bg-red-100 text-red-700 rounded-full text-[9px] font-black uppercase tracking-widest border border-red-200">
                                <span class="h-1.5 w-1.5 rounded-full bg-red-500 mr-2 animate-pulse"></span>
                                76% Importance
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Recommendation Card 2 --}}
                <div class="group relative bg-white p-8 rounded-[2.5rem] border border-gray-100 shadow-xl shadow-gray-200/50 transition-all duration-500 hover:shadow-indigo-500/10 hover:-translate-y-1 border-l-8 border-l-amber-500">
                    <div class="flex flex-col md:flex-row items-center gap-8">
                        <div class="shrink-0 h-16 w-16 bg-amber-50 text-amber-500 rounded-2xl flex items-center justify-center font-black italic text-2xl">02</div>
                        
                        <div class="flex-1 text-center md:text-left">
                            <h4 class="text-2xl font-black text-gray-900 tracking-tight uppercase italic leading-none">Break Pad Replacement</h4>
                            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-2">Brake System Integrity</p>
                        </div>

                        <div class="text-center md:text-right">
                            <p class="text-2xl font-black text-gray-900 tracking-tighter italic">RM 178.00</p>
                            <div class="mt-2 inline-flex items-center px-3 py-1 bg-amber-100 text-amber-700 rounded-full text-[9px] font-black uppercase tracking-widest border border-amber-200">
                                <span class="h-1.5 w-1.5 rounded-full bg-amber-500 mr-2"></span>
                                71% Importance
                            </div>
                        </div>
                    </div>
                </div>

                {{-- Recommendation Card 3 --}}
                <div class="group relative bg-white p-8 rounded-[2.5rem] border border-gray-100 shadow-xl shadow-gray-200/50 transition-all duration-500 hover:shadow-indigo-500/10 hover:-translate-y-1 border-l-8 border-l-indigo-600">
                    <div class="flex flex-col md:flex-row items-center gap-8">
                        <div class="shrink-0 h-16 w-16 bg-indigo-50 text-indigo-600 rounded-2xl flex items-center justify-center font-black italic text-2xl">03</div>
                        
                        <div class="flex-1 text-center md:text-left">
                            <h4 class="text-2xl font-black text-gray-900 tracking-tight uppercase italic leading-none">Coolant Liquid Refill</h4>
                            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-2">Fluid Management</p>
                        </div>

                        <div class="text-center md:text-right">
                            <p class="text-2xl font-black text-gray-900 tracking-tighter italic">RM 110.00</p>
                            <div class="mt-2 inline-flex items-center px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-[9px] font-black uppercase tracking-widest border border-indigo-200">
                                <span class="h-1.5 w-1.5 rounded-full bg-indigo-500 mr-2"></span>
                                28% Importance
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Footer Summary -->
                <div class="bg-slate-50 p-8 rounded-[2.5rem] border border-gray-100 mt-8 text-center md:text-left">
                    <div class="flex flex-col md:flex-row justify-between items-center">
                        <div>
                            <h4 class="text-sm font-black text-gray-900 uppercase tracking-widest italic">Total Estimated Maintenance</h4>
                            <p class="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Calculated based on current AI selection</p>
                        </div>
                        <div class="mt-4 md:mt-0">
                            <p class="text-4xl font-black text-indigo-600 tracking-tighter italic leading-none">RM 538.00</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection